### PR TITLE
Gh-3229: Tinkerpop predicate serialisation bug

### LINKED ISSUE #3229: TInkerpop Predicates can't be serialised
**Describe the bug**
We currently use the Tinkerpop `P` class and extract the predicates to be used from it directly but this class cannot be deserialised so fails if using an accumulo store. We should probably just translate these to Koryphe ones instead.

### PR DESCRIPTION
**Pull request by p29876**
# Related issue

- Resolve #3229

### CODE REVIEW

**Review by cn337131 — APPROVED** [review]

File: library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java [hunk 1]
```diff
@@ -158,14 +161,70 @@ private List<String> getRequestedLabels() {
...
+            return null;
+        }
+
+        View.Builder viewBuilder = new View.Builder();
+        if (viewElementDefinition instanceof GlobalViewElementDefinition) {
+            // Apply filters to all vertices
+            viewBuilder.globalElements((GlobalViewElementDefinition) viewElementDefinition);
+        } else {
+            // Apply filters to each of the labels
+            labels.stream()
```
Comment (tb06904) [inline library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java:185]: No need to stream `List` is iterable so can do `forEach`

File: library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java [hunk 2]
```diff
@@ -158,14 +161,70 @@ private List<String> getRequestedLabels() {
...
+            return null;
+        }
+
+        View.Builder viewBuilder = new View.Builder();
+        if (viewElementDefinition instanceof GlobalViewElementDefinition) {
+            // Apply filters to all edges
+            viewBuilder.globalEdges((GlobalViewElementDefinition) viewElementDefinition);
+        } else {
+            // Apply filters to each of the labels
+            labels.stream()
```
Comment (tb06904) [inline library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java:211]: No need to stream `List` is iterable so can do `forEach`

**Review by tb06904 — COMMENTED** [review]
Very minor points otherwise looks good!

**Review by cn337131 — APPROVED** [review]

**Review by l46978 — APPROVED** [review]
