### PR TITLE
Gh-2917: ProxyStore dynamic GetTraits handler

### LINKED ISSUE #2917: ProxyStore getTraits is static
**Describe the bug**
from #2581 changes the GetTraits Handler get traits from remote store. this is set/static at time of creation. this will not work if the Proxy is pointed towards a FederatedStore

**Expected behavior**
The ProxyStore should get updated traits for a remote FederatedStore when traits are added or removed.

**Additional context**
Likely a new Proxy GetTraitsHandler is required.

### PR DESCRIPTION
**Pull request by GCHQDeveloper314**
# Related Issue

- Resolve #2917

### CODE REVIEW

File: store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java [hunk 1]
```diff
@@ -143,8 +142,13 @@ public boolean isSupported(final Class<? extends Operation> operationClass) {
         return getSupportedOperations().contains(operationClass);
     }
 
-    protected Set<StoreTrait> fetchTraits() throws OperationException {
-        Set<StoreTrait> newTraits = executeOpChainViaUrl(new OperationChain<>(new GetTraits.Builder().currentTraits(false).build()), new Context());
+    protected Set<StoreTrait> fetchTraits(final Operation operation) throws OperationException {
+        Set<StoreTrait> newTraits;
+        try {
+            newTraits = executeOpChainViaUrl(new OperationChain<>(operation), new Context());
+        } catch (final OperationException e) {
```
Comment (GCHQDev404) [inline store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java:149]: can the catch go at the end. catch everything and anything please.

Comment (GCHQDeveloper314) [reply store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java]: Done

**Review by GCHQDev404 — APPROVED** [review]

**Review by t92549 — APPROVED** [review]
