### PR TITLE
gh-2764 get default graphs bug

### LINKED ISSUE #2764: FederatedStore: Review and test "isDisabledByDefault"
**UPDATE: We have now decided that isDisabledByDefault will be removed from Gaffer. As such this ticket is now to delete isDisabledByDefault;**

Class: FederatedStoreDefaultGraphsTest
Add tests and examine the interaction between `isDisabledByDefault` and `StoreConfiguredGraphIds` List
Add tests and examine the interaction between `isDisabledByDefault` and `getGraphs` with Admin privilege.

---

Class: FederatedGraphStorage
Method: GetStream
Line: ~331 `.filter(entry -> !entry.getKey().isDisabledByDefault())`
Review the requirement, usage and test coverage of isDisabledByDefault.

----

Class: FederatedStore
Method: GetDefaultGraphs
line: ~ 549 `if (isNull(adminConfiguredDefaultGraphIdsCSV) || isAdminRequestingOverridingDefaultGraphs) {`
Review the interaction, usage and test coverage with `isDisabledByDefault`. is disabled logic preserved or is it required. 

---

Class: FederatedGraphStorageTest
Method: shouldGetDisabledGraphWhenGetAll
line: ~217
disabledByDefault access is used, but `getAll()` has auths parameter so when and why is it disabled?

---
Class: FederatedGraphStorageTest
Method: shouldNotGetDisabledGraphForAuthUserWhenNoIdsProvided
line: ~287
examine the use of `null` why is it only missing when `get(null)`

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related Issue

- Resolve #2764

### CODE REVIEW

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/access/predicate/FederatedGraphAccessPredicate.java [hunk 1]
```diff
@@ -35,7 +35,7 @@ public FederatedGraphAccessPredicate(final Predicate<User> userPredicate) {
     @Override
     protected boolean isAdministrator(final User user, final String adminAuth) {
         return (!isNull(user)
-                && isNotEmpty(adminAuth)
+                && (isNotEmpty(adminAuth) || user.getUserId().equals("FederatedStoreSystemUser"))
```
Comment (r32575) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/access/predicate/FederatedGraphAccessPredicate.java:38]: `FederatedStoreSystemUser` could be a constant...

**Review by lb324567 — DISMISSED** [review]

**Review by r32575 — DISMISSED** [review]

**Review by lb324567 — DISMISSED** [review]

**Review by GCHQDeveloper314 — APPROVED** [review]

**Review by lb324567 — APPROVED** [review]
