### PR TITLE
Gh 2717 tests failing on windows

### LINKED ISSUE #2717: Tests involving Hadoop/Accumulo do not work on Windows
While looking at #2591 it was discovered that tests involving Hadoop/Accumulo do not work on Windows.

For Hadoop "Native IO is mandatory on Windows and without it you will not be able to get your installation working" ([from Hadoop Wiki](https://cwiki.apache.org/confluence/display/HADOOP2/Hadoop2OnWindows)). This involves installing Hadoop libraries, setting the `HADOOP_HOME` environment variable and compiling and installing Native IO for windows. The Hadoop Native IO libraries for Windows are not distributed by Apache and must either be built from source or downloaded from a 3rd party.

Due to the above situation with Hadoop, all modules which have a test dependency on Hadoop fail to run tests on Windows. This includes at least `hdfs-library`,`accumulo-store`,`accumulo-rest`(plus most other rest modules), `flink-library` and all `spark` modules. 

In addition there is what could be a separate problem with flink and JUnit where a temp directory cannot be deleted.

```
[ERROR] uk.gov.gchq.gaffer.flink.integration.operation.handler.AddElementsFromKafkaHandlerIT.shouldAddElementsWithByteArrayConsumer  Time elapsed: 8.093 s  <<< ERROR!
java.io.IOException: Failed to delete temp directory C:\Users\User\AppData\Local\Temp\junit5479111707429912277. The following paths could not be deleted (see suppressed exceptions for details): , kafkaLogDir, kafkaLogDir\51c41179-8027-4641-b8ff-7d191bafdcb5-0, kafkaLogDir\51c41179-8027-4641-b8ff-7d191bafdcb5-0\00000000000000000000.timeindex
        at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:280)
        at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:188)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        ...
        Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\User\AppData\Local\Temp\junit5479111707429912277
                at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
                at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
                at java.nio.file.Files.delete(Files.java:1126)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:228)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:223)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:199)
                at java.nio.file.Files.walkFileTree(Files.java:2688)
                at java.nio.file.Files.walkFileTree(Files.java:2742)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:199)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:186)
                ... 63 more
        Suppressed: java.nio.file.FileSystemException: C:\Users\User\AppData\Local\Temp\junit5479111707429912277\kafkaLogDir\51c41179-8027-4641-b8ff-7d191bafdcb5-0\00000000000000000000.timeindex: The process cannot access the file because it is being used by another process.
                at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
                at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
                at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
                at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
                at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
                at java.nio.file.Files.delete(Files.java:1126)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:228)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:218)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:199)
                at java.nio.file.Files.walkFileTree(Files.java:2670)
                at java.nio.file.Files.walkFileTree(Files.java:2742)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:199)
                at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:186)
                ... 63 more
```

There's also a potential path problem with path path processing in `common-rest` which may just be linked to Hadoop:
```
[ERROR] Failures:
[ERROR]   DefaultGraphFactoryTest.shouldThrowRuntimeExceptionIfGraphLibraryClassDoesNotExist:55
Expecting message to be:
  "Unable to deserialise graph config"
but was:
  "Illegal char <:> at index 2: /C:/Users/User/Documents/Gaffer/rest-api/common-rest/target/test-classes/store.properties"
Throwable that failed the check:
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/User/Documents/Gaffer/rest-api/common-rest/target/test-classes/store.properties
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at uk.gov.gchq.gaffer.store.StoreProperties.loadStoreProperties(StoreProperties.java:135)
        at uk.gov.gchq.gaffer.rest.factory.DefaultGraphFactory.createGraphBuilder(DefaultGraphFactory.java:97)
        at uk.gov.gchq.gaffer.rest.factory.GraphFactory.createGraph(GraphFactory.java:55)
        at uk.gov.gchq.gaffer.rest.factory.DefaultGraphFactory.getGraph(DefaultGraphFactory.java:71)
        at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
        at org.assertj.core.api.ThrowableTypeAssert.isThrownBy(ThrowableTypeAssert.java:59)
        at uk.gov.gchq.gaffer.rest.factory.DefaultGraphFactoryTest.shouldThrowRuntimeExceptionIfGraphLibraryClassDoesNotExist(DefaultGraphFactoryTest.java:54)
```

### PR DESCRIPTION
**Pull request by lb324567**
Most tests have been fixed, but there are 6 that have been skipped instead as I wasn't able to get those Spark tests working on Windows

# Related Issue

- Resolve #2717

### CODE REVIEW

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/LegacySupportTest.java [hunk 1]
```diff
@@ -52,125 +54,98 @@
...
+
+    @BeforeEach
+    public void setUp() {
+        conf = new Configuration();
+        tempDir = Files.createTempDir();
+    }
+
+    @AfterEach
+    public void cleanUp() {
+        tempDir.deleteOnExit();
```
Comment (GCHQDeveloper314) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/LegacySupportTest.java:68]: This deletion method works because the file is no longer in use when it comes to be deleted, as the deletion occurs [only when the JVM exits](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#deleteOnExit--), not during the tests. Instead of using before/after each, all could be used if each of the 4 tests that create a file used a different filename.

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/LegacySupportTest.java [hunk 2]
```diff
@@ -52,125 +54,98 @@
...
 
-    @TempDir
-    static File tempDir;
+    File tempDir;
+    Configuration conf;
+
+    @BeforeEach
+    public void setUp() {
+        conf = new Configuration();
+        tempDir = Files.createTempDir();
```
Comment (GCHQDeveloper314) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/LegacySupportTest.java:63]: This method is from Guava and is [deprecated since Java 7.](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/io/Files.html#createTempDir()) The recommendation is to use [`Files.createTempDirectory` from Java native `Files`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempDirectory-java.lang.String-java.nio.file.attribute.FileAttribute...-).
```suggestion
        tempDir = Files.createTempDirectory(this.getClass().getName()).toFile();
```

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/impl/CreateSplitPointsTest.java [hunk 3]
```diff
@@ -18,19 +18,20 @@
 
 import com.google.common.collect.Lists;
 import org.apache.commons.codec.binary.Base64;
+import org.apache.commons.lang3.SystemUtils;
+import org.apache.curator.shaded.com.google.common.io.Files;
```
Comment (GCHQDeveloper314) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/impl/CreateSplitPointsTest.java:22]: See comments left on `LegacySupportTest.java` about this import and Temporary files.

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactoryTest.java [hunk 4]
```diff
@@ -415,12 +420,8 @@ private JobConf createLocalConf() {
         return conf;
     }
 
-    private java.nio.file.Path Paths(java.nio.file.Path tempDir, String inputDir) {
-        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
-    }
-
     public static final class TextMapperGeneratorImpl extends TextMapperGenerator {
-        public TextMapperGeneratorImpl() {
+        TextMapperGeneratorImpl() {
```
Comment (GCHQDeveloper314) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactoryTest.java:424]: Might be worth making this inner class private, it's only used in this class. The visibility of the constructor is less important then.

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactoryTest.java [hunk 5]
```diff
@@ -135,42 +138,102 @@ public void shouldSetupJob() throws IOException {
...
+        if (SystemUtils.IS_OS_WINDOWS) {
+            alterPathForWindows(splitsFile);
+        }
+        assertEquals(splitsFile, job.getConfiguration().get(GafferRangePartitioner.class.getName() + ".cutFile"));
     }
 
     @Test
     public void shouldNotSetupAccumuloPartitionerWhenSetupJobAndPartitionerFlagIsFalse() throws IOException {
-        setupAccumuloPartitionerWithGivenPartitioner(NoPartitioner.class);
+        // setupAccumuloPartitionerWithGivenPartitioner(NoPartitioner.class);
```
Comment (GCHQDeveloper314) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactoryTest.java:205]: Commented out code.

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactoryTest.java [hunk 6]
```diff
@@ -135,42 +138,102 @@ public void shouldSetupJob() throws IOException {
...
+            alterPathForWindows(splitsFile);
+        }
+        assertEquals(splitsFile, job.getConfiguration().get(GafferRangePartitioner.class.getName() + ".cutFile"));
+
     }
 
     @Test
     public void shouldSetupAccumuloPartitionerWhenSetupJobAndPartitionerIsNull() throws IOException {
-        setupAccumuloPartitionerWithGivenPartitioner(null);
+        // setupAccumuloPartitionerWithGivenPartitioner(null);
```
Comment (GCHQDeveloper314) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactoryTest.java:178]: Commented out code.

**Review by GCHQDeveloper314 — CHANGES_REQUESTED** [review]
Comments are mostly around code style or minor syntax changes.

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/AddUpdateTableIteratorTest.java [hunk 7]
```diff
@@ -42,20 +41,14 @@
...
     private static final String SCHEMA_2_DIR = "src/test/resources/schema2";
     private static final String STORE_PROPS_PATH = "src/test/resources/store.properties";
     private static final String STORE_PROPS_2_PATH = "src/test/resources/store2.properties";
-    private static final String STORE_PROPS_PATH_UPDATED = "src/test/resources/current_store.properties";
-    private static final String STORE_PROPS_2_PATH_UPDATED = "src/test/resources/current_store2.properties";
     private static final String EMPTY_STORE_PROPS_PATH = "src/test/resources/empty-store.properties";
     private static final String FILE_GRAPH_LIBRARY_TEST_PATH = "target/graphLibrary";
 
-    private static final AccumuloProperties PROPERTIES_1 = AccumuloProperties.loadStoreProperties(STORE_PROPS_PATH);
-    private static final AccumuloProperties PROPERTIES_2 = AccumuloProperties.loadStoreProperties(STORE_PROPS_2_PATH);
```
[the remark this answers is not in the document]
Comment (GCHQDeveloper314) [reply store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/AddUpdateTableIteratorTest.java:57]: These are unused, resolved.

File: core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java [hunk 8]
```diff
@@ -293,25 +288,13 @@ public void shouldConstructGraphFromSchemaURI() throws IOException, URISyntaxExc
...
-            graph = new Graph.Builder()
-                    .config(new GraphConfig.Builder()
-                            .graphId(GRAPH_ID)
-                            .build())
-                    .storeProperties(storeInputUri)
-                    .addSchemas(typeInputUri, schemaInputUri)
-                    .build();
-        } finally {
-            if (schemaDir != null) {
-                FileUtils.deleteDirectory(schemaDir);
```
[the remark this answers is not in the document]
Comment (lb324567) [reply core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java:312]: I removed this because of that, for some reason it kept trying to delete the directory even though it wasn't there. So it was throwing an error because there was nothing to delete.

File: core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java [hunk 9]
```diff
@@ -1795,7 +1781,8 @@ public void shouldBuildGraphFromConfigAndSetIdsToGraphsWhenGraphSchemaAndStorePr
         assertEquals(graphId1, graph1.getGraphId());
         JsonAssert.assertEquals(library.getSchema(SCHEMA_ID_1).toJson(false), librarySchema.toJson(false));
         // Check that the schemaId = schemaId1 as both the supplied schema id is null
-        // Check that the storePropsId = storePropertiesId1 as the supplied storeProps id is null
+        // Check that the storePropsId = storePropertiesId1 as the supplied storeProps
+        // id is null
```
[the remark this answers is not in the document]
Comment (lb324567) [reply core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java:1785]: This was done automatically by VS code. I can fix this if it's a problem? I don't think it's causing any harm which is why i left it.

File: rest-api/common-rest/src/test/java/uk/gov/gchq/gaffer/rest/factory/DefaultGraphFactoryTest.java [hunk 10]
```diff
@@ -37,16 +39,20 @@ public void clearSystemProperties() {
     @Test
     public void shouldThrowRuntimeExceptionIfGraphLibraryClassDoesNotExist() {
         // Given
-        String schemaPath = getClass().getResource("/schema").getPath();
-        String storePropsPath = getClass().getResource("/store.properties").getPath();
+        // Need to use getAbsolutePath so the test works on Windows
+        File schemaFile = new File(getClass().getResource("/schema").getFile());
+        String schemaPath = schemaFile.getAbsolutePath();
+        File propsFile = new File(getClass().getResource("/store.properties").getFile());
+        String storePropsPath = propsFile.getAbsolutePath();
```
[the remark this answers is not in the document]
Comment (lb324567) [reply rest-api/common-rest/src/test/java/uk/gov/gchq/gaffer/rest/factory/DefaultGraphFactoryTest.java:46]: I'd rather keep it on 2 lines, i personally find it easier to read.

[the remark this answers is not in the document]
Comment (GCHQDeveloper314) [reply rest-api/common-rest/src/test/java/uk/gov/gchq/gaffer/rest/factory/DefaultGraphFactoryTest.java]: This (or other variations) would avoid having it all on one line, without needing an extra variable:
```java
String schemaPath = new File(getClass().getResource("/schema")
                            .getFile()).getAbsolutePath();
```

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/AddUpdateTableIteratorTest.java [hunk 11]
```diff
@@ -130,18 +124,25 @@ public void shouldReturnStoreClassNameNotFoundWhenStorePropsIsEmpty() throws Exc
...
+            expectedMessage = "Failed to load store properties file : invalid\\file\\path";
+        } else {
+            expectedMessage = "Failed to load store properties file : invalid/file/path";
+        }
+
         assertThatExceptionOfType(RuntimeException.class)
-                .isThrownBy(() -> AddUpdateTableIterator.main(args))
-                .withMessage("Failed to load store properties file : invalid/file/path");
+            .isThrownBy(() -> AddUpdateTableIterator.main(args))
+            .withMessage(expectedMessage);
```
Comment (GCHQDeveloper314) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/AddUpdateTableIteratorTest.java:146]: Regex based matching can be used here to cover both cases concisely, without custom variables:
```java
 assertThatExceptionOfType(RuntimeException.class)
     .isThrownBy(() -> AddUpdateTableIterator.main(args))
     .withMessageMatching("Failed to load store properties file : invalid[\\\/]{1,2}file[\\\/]{1,2}path");
```

Comment (lb324567) [reply store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/AddUpdateTableIteratorTest.java]: Done, solution slightly different due to regex problems.

**Review by GCHQDeveloper314 — APPROVED** [review]
Previous review comments addressed, apart from some around code style. Others can express their thoughts about that.

**Review by p3430233 — APPROVED** [review]
