### PR TITLE
Gh 2890 cache service static instance bug

### LINKED ISSUE #2890: Cache Service Static Instance Bug
**Describe the bug**
Cache service is Static, which means that any attempt to use a new cache can wipe/swap the cache.
This is horrendous for FederatedStore which uses the cache to store graphs. This is an Ancient bug but since the internal GraphStorage java object has been removed since #2595 this bug has appeared during docker containers testing.

Truth Table of error and behaviour below.

**To Reproduce**
  | AddGraph with no Cache | AddGraph with HashMap Cache | AddGraph with JCS Cache
-- | -- | -- | --
FederatedStore is currently using HashMap Cache | Graph is added to HashMap Cache | The Cache service continues to be HashMap Cache, the cache is initialised, FederatredStore only contains this new graph. | The Cache service is switched to JCS Cache, the cache is initialised, JCS cache is loaded from disc, FederatredStore contains this new graph and anything pre-existing in the cache.
FederatedStore is currently using JCS Cache | Graph is added to JCS Cache | The Cache service is switched to HashMap Cache, the cache is initialised, FederatredStore only contains this new graph. | The Cache service continues to be JCS Cache, the cache is initialised, JCS cache is loaded from disc, FederatredStore contains this new graph and anything pre-existing in the cache.

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related Issue

- Resolve #2890

### CODE REVIEW

File: core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedOperationCacheBackwardCompatibilityTest.java [hunk 1]
```diff
@@ -1,68 +0,0 @@
...
-import uk.gov.gchq.gaffer.operation.OperationChain;
-import uk.gov.gchq.gaffer.operation.impl.add.AddElements;
-import uk.gov.gchq.gaffer.user.User;
-
-import java.util.Properties;
-
-import static java.util.Arrays.asList;
-import static org.junit.jupiter.api.Assertions.assertEquals;
-
-public class NamedOperationCacheBackwardCompatibilityTest {
```
Comment (t92549) [inline core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedOperationCacheBackwardCompatibilityTest.java:35]: How come 2 of the backward compatibility tests have been deleted?

File: core/cache/src/main/java/uk/gov/gchq/gaffer/cache/CacheServiceLoader.java [hunk 2]
```diff
@@ -56,6 +56,12 @@ public static void initialise(final Properties properties) {
             }
             return;
         }
+
+        if (isEnabled()) {
```
Comment (t92549) [inline core/cache/src/main/java/uk/gov/gchq/gaffer/cache/CacheServiceLoader.java:60]: I think there needs to be a test added which fails before this change and passes to prove it works

Comment (GCHQDev404) [reply core/cache/src/main/java/uk/gov/gchq/gaffer/cache/CacheServiceLoader.java:60]: This was added because test were failing.

File: core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedOperationCacheBackwardCompatibilityTest.java (hunk 1 above)
Comment (t92549) [reply core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedOperationCacheBackwardCompatibilityTest.java:35]: These will be re-added before 2.0 release: https://github.com/gchq/Gaffer/issues/2895

**Review by t92549 — APPROVED** [review]
