### PR TITLE
Gh-2858: Fix ImportExportIT and ToCsvHandler

### LINKED ISSUE #2858: Fix ImportExportIT
Due to a bug with `readFile` the test is only testing the input file is the same as itself.
https://github.com/gchq/Gaffer/blob/adfa1163842872765ac290d124062029f5d6c5ca/integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java#L115

### PR DESCRIPTION
**Pull request by t92549**
# Related Issue

- Resolve #2858

### CODE REVIEW

File: integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java [hunk 1]
```diff
@@ -96,23 +95,22 @@ public void shouldImportFromFileThenExportBackOutToDifferentFile() throws Operat
...
-
-        //   When
-
         Iterable<String> incomingFile = readFile(INCOMING_FILE_PATH);
         Iterable<String> outgoingFile = readFile(path.toFile().getAbsolutePath());
 
 
-        //  Then
+        // Then
+        assertThat(expectedData).containsExactlyInAnyOrderElementsOf(exportedData);
```
Comment (GCHQDeveloper314) [inline integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java:105]: Might be better if it was asserting that the exported data contained the expected data and not the other way around, as normally we assert that what we have contains what we expect.

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java [hunk 2]
```diff
@@ -73,15 +74,18 @@ private LinkedHashMap<String, String> getPropertyHeadersFromSchema(final Store s
...
             }
-            for (final String propertyName:schemaEdgeDefinition.getProperties()) {
-                String typeName = schemaEdgeDefinition.getPropertyTypeName(propertyName);
-                propertyHeadersFromSchema.put(propertyName, schema.getType(typeName).getClazz().getSimpleName());
+            for (final String propertyName : schemaEdgeDefinition.getProperties()) {
+                final String typeName = schemaEdgeDefinition.getPropertyTypeName(propertyName);
+                final String javaType = schema.getType(typeName).getClazz().getSimpleName();
+                final String openCypherType = OpenCypherFormat.typeMappings.getOrDefault(javaType, javaType);
+
+                propertyHeadersFromSchema.put(propertyName, openCypherType);
```
Comment (GCHQDeveloper314) [inline core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java:88]: This change to use the `OpenCypherFormat.typeMappings` is causing tests to fail because they don't expect the OpenCypher `Int`.

The test failure is confusing because the asserts in there are also backwards, causing the error to reported that it expected `Int` but was `Integer`, when it is actually the other way around in the code.

I think it would be better if the mapping between Java and OpenCypher types was done in a separate for loop after these ones. Is there a reason why the identifier type doesn't need to be converted to a OpenCypher one?

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java [hunk 3]
```diff
@@ -73,15 +74,18 @@ private LinkedHashMap<String, String> getPropertyHeadersFromSchema(final Store s
             }
         }
         for (final SchemaEdgeDefinition schemaEdgeDefinition : schema.getEdges().values()) {
-            for (final IdentifierType identifierType:schemaEdgeDefinition.getIdentifiers()) {
+            for (final IdentifierType identifierType : schemaEdgeDefinition.getIdentifiers()) {
                 if (identifierType.toString().equals(identifierType.DIRECTED.toString())) {
```
Comment (GCHQDeveloper314) [inline core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java:78]: This should also be improved. There's no reason to convert this all to strings and then compare. This can be done instead:
```suggestion
                if (identifierType.equals(IdentifierType.DIRECTED)) {
```

**Review by GCHQDeveloper314 — CHANGES_REQUESTED** [review]

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java (hunk 2 above)
Comment (t92549) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java:88]: The type mapping is only relevant for properties as only property headings have types. I have sorted the broken tests now

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java (hunk 3 above)
Comment (t92549) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java]: Have implemented your suggestion

File: integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java (hunk 1 above)
Comment (t92549) [reply integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java]: Managed to fix and get this in

File: integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java [hunk 4]
```diff
@@ -96,23 +95,22 @@ public void shouldImportFromFileThenExportBackOutToDifferentFile() throws Operat
...
-
-        //   When
-
         Iterable<String> incomingFile = readFile(INCOMING_FILE_PATH);
         Iterable<String> outgoingFile = readFile(path.toFile().getAbsolutePath());
 
 
-        //  Then
+        // Then
+        assertThat((Iterable<String>) exportedData).containsExactlyInAnyOrderElementsOf(expectedData);
```
Comment (GCHQDeveloper314) [inline integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java:105]: It might be cleaner to put the cast with the `graph.execute` and not therefore not using the `?` at all.

**Comment by GCHQDeveloper314** [comment]
The failing test should be fixed by changes in #2842, once that has been merged this PR should be ready to merge.

**Review by GCHQDeveloper314 — APPROVED** [review]

**Review by lb324567 — APPROVED** [review]

**Review by t11947 — APPROVED** [review]

**Review by GCHQDev404 — APPROVED** [review]
