### PR TITLE
Gh-3046: Fix spring-rest to allow schema with no entities

### LINKED ISSUE #3046: Cannot start spring-rest with only edges in schema
**Describe the bug**
The spring-rest cannot be started when your schema only has edge groups and no entity groups.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create schema with an edge group but no entity group
2. Start spring-rest pointing to this schema
3. NullPointerException crash

**Expected behaviour**
The spring-rest should be able to start with any legal Gaffer schema.

**Additional context**
This is due to the `AbstractExamplesFactory`, as can be seen in the stack trace below. The `GetWalks` example function creates an empty example if there are no edge groups in the schema, but unlike the other example functions, this check is not done for entity groups. Therefore, when trying to create a populated `GetWalks` example, it uses the entity group from the schema which causes a null pointer exception.

**Stack trace and errors**
```
Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at uk.gov.gchq.gaffer.rest.GafferWebApplication.main(GafferWebApplication.java:27)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createExamplesFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        ... 19 more
Caused by: java.lang.NullPointerException
        at uk.gov.gchq.gaffer.rest.factory.AbstractExamplesFactory.getEntityId(AbstractExamplesFactory.java:212)
        at uk.gov.gchq.gaffer.rest.factory.AbstractExamplesFactory.getWalks(AbstractExamplesFactory.java:455)
        at uk.gov.gchq.gaffer.rest.factory.AbstractExamplesFactory.generateExamples(AbstractExamplesFactory.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        ... 32 more
```

### PR DESCRIPTION
**Pull request by t92549**
# Related issue

- Resolve #3046

### CODE REVIEW

File: rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java [hunk 1]
```diff
@@ -448,7 +448,7 @@ public ToMap toMap() {
 
     public GetWalks getWalks() {
         final List<String> edges = new ArrayList<>(getSchema().getEdgeGroups());
-        if (edges.isEmpty()) {
+        if (edges.isEmpty() || getSchema().getEntityGroups().isEmpty()) {
```
Comment (GCHQDev404) [inline rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java:451]: So this is a lot more slimmer than the version we worked through, where we changed `getEntityId` and `getEdgeId`

Comment (GCHQDev404) [reply rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java:451]: Seems to off/on with the cache graphs fine tho. so it works.

**Review by GCHQDeveloper314 — APPROVED** [review]
The examples only work with the old REST and not Spring REST (see #2685). As such, it seems a little odd that this code is run at all. It might be better to disable this entirely for Spring, as it's not doing anything useful and also pollutes the logs at startup.

File: rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java (hunk 1 above)
Comment (t92549) [reply rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java:451]: The NPE was happening inside `getEntityId`, but every other usage of that function was checked, so I simply added a check here, rather than adding checks inside `getEntityId`.

**Comment by t92549** [comment]
> The examples only work with the old REST and not Spring REST (see #2685). As such, it seems a little odd that this code is run at all. It might be better to disable this entirely for Spring, as it's not doing anything useful and also pollutes the logs at startup.

Perhaps, however, it might just be better to implement #2685.
