### PR TITLE
Gh-3166: FederatedStore While Operation Looping Bug

### LINKED ISSUE #3166: FederatedStore While Operation Looping Bug
**Describe the bug**
A While operation performed on the FederatedStore incorrectly triggers an infinite looping exception.

**To Reproduce**
Perform an operation chain within the While or Join. The operation chain chain should contain a operation which is not overridden with using a FederatedStore specific Handler.

**Expected behaviour**
While loops and joins of the operations should not trigger an "federated infinite looping" exception.

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related issue

- Resolve #3166

### CODE REVIEW

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/WhileHandler.java [hunk 1]
```diff
@@ -60,16 +60,20 @@ public Object doOperation(final While operation,
...
                 break;
             }
-            input = doDelegateOperation(input, operationClone.getOperation(), context, store);
+            input = doDelegateOperation(input, getOperationFromWhile(clonedWhile), context, store);
         }
 
         return input;
     }
 
+    protected Operation getOperationFromWhile(final While aWhile) {
```
Comment (t92549) [inline core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/WhileHandler.java:73]: Maybe a comment to explain this is useful for overriding (in Federation)?

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedWhileLoopAndJoinTest.java [hunk 2]
```diff
@@ -0,0 +1,280 @@
...
+                new AddGraph.Builder()
+                        .graphId(GRAPH_ID_ACCUMULO)
+                        .storeProperties(storeProperties)
+                        .schema(schema)
+                        .parentSchemaIds(null)
+                        .parentPropertiesId(null)
+                        .isPublic(true)
+                        .build()), context);
+
+        final Operation operation = JSONSerialiser.deserialise("{\n" +
```
Comment (t92549) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedWhileLoopAndJoinTest.java:124]: Might be easier to read as Java objects rather than string

Comment (GCHQDev404) [reply store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedWhileLoopAndJoinTest.java:124]: Probably, the operation came from another team as JSON.

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/WhileHandler.java (hunk 1 above)
Comment (GCHQDev404) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/WhileHandler.java:73]: I thought the rule was anything Federation should not be mentioned lower down in the Gaffer code?
Thoughts?

Comment (GCHQDeveloper314) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/WhileHandler.java:73]: I don't think we should mention Federation in the core code. It is an additional store which _shouldn't_ require changes to the core or mentions of Federation. In practice there are a few things like this. It will be easy to find out what this is for. A general JavaDoc comment would be good but a comment which just says that it's there for Federation less so.

**Review by GCHQDeveloper314 — CHANGES_REQUESTED** [review]

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedWhileHandler.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+ * @see WhileHandler
+ */
+public class FederatedWhileHandler extends WhileHandler {
+
+    /**
+     * Gets an Operation from a While, but with a clone.
+     * This avoids a false looping error being detected by the FederatedStore.
+     *
+     * @param aWhile The while to get operation from
+     * @return The Operation with a deep clone of the options field.
```
[the remark this answers is not in the document]
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedWhileHandler.java:36]: Javadoc is out of date in since older commit.

Comment (GCHQDev404) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedWhileHandler.java:36]:
```suggestion
     * @return The Operation with a clone of the options field.
```

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedJoinHandler.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+
+public class FederatedJoinHandler<I> extends JoinHandler<I> {
+
+
+    /**
+     * Gets an Operation from a Join, but with a clone.
+     * This avoids a false looping error being detected by the FederatedStore.
+     *
+     * @param join The Join to get operation from
+     * @return The Operation with a deep clone of the options field.
```
[the remark this answers is not in the document]
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedJoinHandler.java:31]:
```suggestion
     * @return The Operation with a clone of the options field.
```

**Review by GCHQDeveloper314 — APPROVED** [review]

**Review by tb06904 — APPROVED** [review]
