### PR TITLE
Gh 2906 federatedstore removegraph must clear all associated caches

### LINKED ISSUE #2906: FederatedStore RemoveGraph must clear all associated caches
**Describe the bug**
FederatedStore RemoveGraph must clear all associated caches
else a 2nd graph added with the pre-existing cache will have namedOperations pre-existing.
make it a flag of RemoveGraph ?

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related Issue

- Resolve #2906

### CODE REVIEW

**Review by GCHQDeveloper314 — CHANGES_REQUESTED** [review]
This PR contains duplicate commits which are also in the PR for 2903. Looks like most of the diff is duplicate.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java [hunk 1]
```diff
@@ -163,21 +169,25 @@ public Collection<GraphSerialisable> getAll(final User user) {
...
+        return remove(graphId, federatedAccess -> federatedAccess.hasWriteAccess(user, adminAuth), removeCache);
     }
 
-    private boolean remove(final String graphId, final Predicate<FederatedAccess> accessPredicate) {
+    private boolean remove(final String graphId, final Predicate<FederatedAccess> accessPredicate, final boolean removeCache) {
         FederatedAccess accessFromCache = federatedStoreCache.getAccessFromCache(graphId);
         boolean rtn;
         if (nonNull(accessFromCache) && accessPredicate.test(accessFromCache)) {
+
+            removeGraphCaches(graphId, removeCache);
```
Comment (t92549) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:189]: I think this function should not have a boolean passed through to it, but instead should only be executed if `removeCache` is true. Effectively, remove the if statement from within the function and put it here

**Review by t92549 — APPROVED** [review]
