### PR TITLE
gh-2571: Fixed matchedVertex behaviour and added new ITs

### LINKED ISSUE #2571: Improve and test Accumulo matched vertex behaviour
After removing `SeedMatching` in #2552, we decided that the `includeMatchedVertex` flag should be set depending on the operation. It should only be true when there are only EntityIds in the input. As well as this, there should be tests to document the fact that sometimes one Edge can be returned twice depending on how it matches with an Entity and Edge input.

https://github.com/gchq/Gaffer/blob/ab0b66c11f99d30d6c9b9f004e09f6166e206188/store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/impl/AccumuloElementsRetriever.java#L31

### PR DESCRIPTION
**Pull request by t92549**
# Related Issue

- Resolve #2571

### CODE REVIEW

File: store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/AccumuloMatchedVertexIT.java [hunk 1]
```diff
@@ -0,0 +1,337 @@
...
+        final List<Edge> edgeResults = getEdgeResults(results);
+
+        // Then
+        assertThat(results).hasSize(1);
+        assertThat(edgeResults).hasSize(0);
+    }
+
+    @ParameterizedTest
+    @MethodSource("getEdgeVariants")
+    public void shouldTest9(Edge edge) throws OperationException {
```
Comment (GCHQDev404) [inline store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/AccumuloMatchedVertexIT.java:260]: name?

**Review by GCHQDev404 — APPROVED** [review]
