### PR TITLE
Gh-2620: Cherry-pick GetElementsWithinSet fix (#2597)

### LINKED ISSUE #2620: Cherry-pick GetElementsWithinSet fix into v2-alpha
Specifically https://github.com/gchq/Gaffer/commit/b8b00162fdaca8d67a4b2179aa2d80a4dab66a74

### PR DESCRIPTION
**Pull request by t92549**
* Fixed bug gh-2562. View properties are now being filtered. Added tests

# Related Issue

- Resolve #2620

### CODE REVIEW

File: store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java [hunk 1]
```diff
@@ -399,7 +408,7 @@ private boolean _hasNext() throws RetrieverException {
                 updateScanner();
             }
             if (!scannerIterator.hasNext()) {
-                scanner.close();
+                CloseableUtil.close(scanner);
```
Comment (t11947) [inline store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java:411]: Worth noting that this swallows the exception whereas the previous method doesn't. Missed raising this in the original.

Comment (r32575) [reply store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java:411]: Not sure... would you care about it not closing correctly? I'll do some digging...

Comment (t92549) [reply store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java:411]: I am not sure either but it seems that, for now, this can just get merged and then be looked at as part of your closeable PR?

**Review by GCHQDeveloper314 — APPROVED** [review]
This is the same as #2597. If we want to make any improvements it might be best to do so in a new PR.

File: store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java (hunk 1 above)
Comment (t92549) [reply store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java:411]: Think maybe this should be looked at separately as suggested here: https://github.com/gchq/Gaffer/pull/2621#pullrequestreview-932162393
