### PR TITLE
Gh 2761 schema tests fixes

### LINKED ISSUE #2761: FederatedStore: default Merge Mapping
continuation of  #2357

Add a default mappings of what merge function to be used for each operation.

This is should include a mapping for getElements which re-applys views. this defeats an issue with:
```
graphA with entityA count 6
graphB with entityA count 11
graphC with entityB count 7
graphD with entityC count 4

getAllElements with view count less than 10

result should be empty
```

### PR DESCRIPTION
**Pull request by t92549**
# Related Issue

- Resolve #2761

### CODE REVIEW

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 1]
```diff
@@ -136,8 +137,7 @@ public void shouldGetCorrectDefaultViewForAChosenGraphOperation() throws Operati
     }
 
     @Test
-    @Disabled //TODO FS OverlappingSchema review
-    public void shouldBeAbleToGetElementsWithOverlappingSchemas() throws OperationException {
+    public void shouldBeAbleToGetElementsWithOverlappingSchemasDefaultBestEffortsMergeFunction() throws OperationException {
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:140]:
```suggestion
    public void shouldBeAbleToGetElementsWithOverlappingSchemasUsingDefaultMergeFunction() throws OperationException {
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 2]
```diff
@@ -148,13 +148,17 @@ public void shouldBeAbleToGetElementsWithOverlappingSchemas() throws OperationEx
...
+        final Iterable<? extends Element> results = (Iterable<? extends Element>) federatedStore.execute(new FederatedOperation.Builder()
+                .op(new GetElements.Builder()
+                        .input(new EntitySeed(SOURCE_BASIC))
+                        .view(new View.Builder()
+                                .edge(GROUP_BASIC_EDGE, new ViewElementDefinition.Builder()
+                                        .properties(PROPERTY_2)
+                                        .build())
                                 .build())
                         .build())
+                .mergeFunction(new DefaultBestEffortsMergeFunction())
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:161]:
```suggestion
                .mergeFunction(uk.gov.gchq.gaffer.federatedstore.util.FederatedStoreUtil.getDefaultMergeFunction())
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 3]
```diff
@@ -211,15 +262,18 @@ public void shouldBeAbleToGetSchemaWithOverlappingSchemas() throws OperationExce
     }
 
     @Test
-    @Disabled //TODO FS OverlappingSchema review
-    public void shouldValidateCorrectlyWithOverlappingSchemas() throws OperationException {
+    public void shouldValidateCorrectlyWithOverlappingSchemasDefaultBestEffortsMergeFunction() throws OperationException {
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:265]:
```suggestion
    public void shouldValidateCorrectlyWithOverlappingSchemasWithDefaultMergeFunction() throws OperationException {
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 4]
```diff
@@ -211,15 +262,18 @@ public void shouldBeAbleToGetSchemaWithOverlappingSchemas() throws OperationExce
...
         addOverlappingPropertiesGraphs(STRING_REQUIRED_TYPE);
 
         // When
         addEdgeBasicWith(DEST_2, 1, 2);
 
-        final Iterable<? extends Element> results = federatedStore.execute(new GetAllElements.Builder().build(), testContext);
+        // DefaultBestEffortsMergeFunction specified - behaves like pre 2.0 aggregation
+        final Iterable<? extends Element> results = (Iterable<? extends Element>) federatedStore.execute(new FederatedOperation.Builder()
+                .op(new GetAllElements())
+                .mergeFunction(new DefaultBestEffortsMergeFunction())
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:275]:
```suggestion
                .mergeFunction(uk.gov.gchq.gaffer.federatedstore.util.FederatedStoreUtil.getDefaultMergeFunction)
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 5]
```diff
@@ -247,8 +318,7 @@ public void shouldThrowValidationMissingPropertyWithOverlappingSchemas() throws
     }
 
     @Test
-    @Disabled //TODO FS OverlappingSchema review
-    public void shouldBeAbleToIngestAggregateWithOverlappingSchemas() throws OperationException {
+    public void shouldBeAbleToIngestAggregateWithOverlappingSchemasDefaultBestEffortsMergeFunction() throws OperationException {
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:321]:
```suggestion
    public void shouldBeAbleToIngestAggregateWithOverlappingSchemasWithDefaultMergeFunction() throws OperationException {
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 6]
```diff
@@ -263,10 +333,14 @@ public void shouldBeAbleToIngestAggregateWithOverlappingSchemas() throws Operati
...
-                .view(new View.Builder()
-                        .edge(GROUP_BASIC_EDGE, new ViewElementDefinition.Builder().build()).build())
+        // DefaultBestEffortsMergeFunction specified - behaves like pre 2.0 aggregation
+        final Iterable<? extends Element> results = (Iterable<? extends Element>) federatedStore.execute(new FederatedOperation.Builder()
+                .op(new GetElements.Builder()
+                        .input(new EntitySeed(SOURCE_BASIC))
+                        .view(new View.Builder()
+                                .edge(GROUP_BASIC_EDGE, new ViewElementDefinition.Builder().build()).build())
+                        .build())
+                .mergeFunction(new DefaultBestEffortsMergeFunction())
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:343]:
```suggestion
                .mergeFunction(uk.gov.gchq.gaffer.federatedstore.util.FederatedStoreUtil.getDefaultMergeFunction())
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 7]
```diff
@@ -295,24 +369,68 @@ public void shouldBeAbleToIngestAggregateWithOverlappingSchemas() throws Operati
...
+                .property(PROPERTY_2, "value2,value2")
+                .build());
+
+        assertThat((Iterable<Edge>) results)
+                .isNotNull()
+                .containsExactlyInAnyOrderElementsOf(expected);
+    }
+
+    @Test
+    public void shouldBeAbleToIngestAggregateMissingPropertyWithOverlappingSchemasDefaultBestEffortsMergeFunction() throws OperationException {
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:413]:
```suggestion
    public void shouldBeAbleToIngestAggregateMissingPropertyWithOverlappingSchemasWithDefaultMergeFunction() throws OperationException {
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 8]
```diff
@@ -295,24 +369,68 @@ public void shouldBeAbleToIngestAggregateWithOverlappingSchemas() throws Operati
...
+
+        // When
+        // DefaultBestEffortsMergeFunction specified - behaves like pre 2.0 aggregation
+        final Iterable<? extends Element> elements = (Iterable<? extends Element>) federatedStore.execute(new FederatedOperation.Builder()
+                .op(new GetElements.Builder()
+                        .input(new EntitySeed(SOURCE_BASIC))
+                        .view(new View.Builder()
+                                .edge(GROUP_BASIC_EDGE, new ViewElementDefinition.Builder().build()).build())
+                        .build())
+                .mergeFunction(new DefaultBestEffortsMergeFunction())
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:431]:
```suggestion
                .mergeFunction(uk.gov.gchq.gaffer.federatedstore.util.FederatedStoreUtil.getDefaultMergeFunction())
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 9]
```diff
@@ -342,8 +459,46 @@ public void shouldBeAbleToIngestAggregateMissingPropertyWithOverlappingSchemas()
...
+                .property(PROPERTY_2, ",")
+                .build());
+
+        assertThat((Iterable<Edge>) elements)
+                .isNotNull()
+                .containsExactlyInAnyOrderElementsOf(expected);
+    }
+
+    @Test
+    public void shouldBeAbleToViewPropertyWithOverlappingSchemasDefaultBestEffortsMergeFunction() throws OperationException {
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:501]:
```suggestion
    public void shouldBeAbleToViewPropertyWithOverlappingSchemasWithDefaultMergeFunction() throws OperationException {
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 10]
```diff
@@ -355,13 +510,17 @@ public void shouldBeAbleToViewPropertyWithOverlappingSchemas() throws OperationE
...
+        final Iterable<? extends Element> results = (Iterable<? extends Element>) federatedStore.execute(new FederatedOperation.Builder()
+                .op(new GetElements.Builder()
+                        .input(new EntitySeed(SOURCE_BASIC))
+                        .view(new View.Builder()
+                                .edge(GROUP_BASIC_EDGE, new ViewElementDefinition.Builder()
+                                        .properties(PROPERTY_2)
+                                        .build())
                                 .build())
                         .build())
+                .mergeFunction(new DefaultBestEffortsMergeFunction())
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:523]:
```suggestion
                .mergeFunction(uk.gov.gchq.gaffer.federatedstore.util.FederatedStoreUtil.getDefaultMergeFunction())
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 11]
```diff
@@ -454,8 +660,7 @@ public void shouldBeAbleToFilterPropertyWithOverlappingSchemas() throws Operatio
     }
 
     @Test
-    @Disabled //TODO FS OverlappingSchema review
-    public void shouldBeAbleToQueryAggregatePropertyWithOverlappingSchemas() throws OperationException {
+    public void shouldBeAbleToQueryAggregatePropertyWithOverlappingSchemasDefaultBestEffortsMergeFunction() throws OperationException {
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:663]:
```suggestion
    public void shouldBeAbleToQueryAggregatePropertyWithOverlappingSchemasDefaultMergeFunction() throws OperationException {
```

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java [hunk 12]
```diff
@@ -467,13 +672,17 @@ public void shouldBeAbleToQueryAggregatePropertyWithOverlappingSchemas() throws
...
+        final Iterable<? extends Element> results = (Iterable<? extends Element>) federatedStore.execute(new FederatedOperation.Builder()
+                .op(new GetElements.Builder()
+                        .input(new EntitySeed(SOURCE_BASIC))
+                        .view(new View.Builder()
+                                .edge(GROUP_BASIC_EDGE, new ViewElementDefinition.Builder()
+                                        .groupBy()
+                                        .build())
                                 .build())
                         .build())
+                .mergeFunction(new DefaultBestEffortsMergeFunction())
```
Comment (GCHQDev404) [inline store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java:685]:
```suggestion
                .mergeFunction(uk.gov.gchq.gaffer.federatedstore.util.FederatedStoreUtil.getDefaultMergeFunction())
```

**Review by GCHQDev404 — APPROVED** [review]
