### PR TITLE
Gh-3139: createExamplesFactory exceptions on startup

### LINKED ISSUE #3139: createExamplesFactory exception on Gaffer startup with valid config
**Describe the bug**
When starting a Gaffer rest api, if there are any configuration issues, they will be thrown as exceptions with the `createExamplesFactory` method. This can make it unclear where actual errors in config arise.

There are even some examples where `createExamplesFactory` will crash due to config, but the config provided is valid. For example: when you have edges in your schema without `directed` set. This is done in some Gaffer test schemas and creates a warning, but crashes the rest api.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a Gaffer REST API with edges in a schema and do not set `directed`
2. Perform an operation over the rest
3. It will error

**Expected behaviour**
Error messages should be clearer. Perhaps config should be checked before the examples made?

**Additional Context**
`createExamplesFactory` is responsible for creating example operations which are used in operation details and for populating the example operation drop down in the core-rest.

**Stack trace and errors**
```
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> A MultiException has 4 exceptions.  They are:</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: A MultiException has 4 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalStateException: Unable to perform operation: post construct on uk.gov.gchq.gaffer.rest.service.v2.example.DefaultExamplesFactory
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of uk.gov.gchq.gaffer.rest.service.v2.OperationServiceV2 errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on uk.gov.gchq.gaffer.rest.service.v2.OperationServiceV2

	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	uk.gov.gchq.gaffer.rest.filter.OriginFilter.doFilter(OriginFilter.java:42)
</pre><p><b>Root Cause</b></p><pre>A MultiException has 4 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalStateException: Unable to perform operation: post construct on uk.gov.gchq.gaffer.rest.service.v2.example.DefaultExamplesFactory
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of uk.gov.gchq.gaffer.rest.service.v2.OperationServiceV2 errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on uk.gov.gchq.gaffer.rest.service.v2.OperationServiceV2

	org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65)
	org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:226)
	org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:59)
	org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:758)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:721)
	org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:691)
	org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:160)
	org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:30)
	org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:105)
	org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:260)
	org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:51)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:86)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:69)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:38)
	org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:247)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	uk.gov.gchq.gaffer.rest.filter.OriginFilter.doFilter(OriginFilter.java:42)
</pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
	uk.gov.gchq.gaffer.rest.factory.AbstractExamplesFactory.isAnEdgeDirected(AbstractExamplesFactory.java:227)
	uk.gov.gchq.gaffer.rest.factory.AbstractExamplesFactory.getEdgeId(AbstractExamplesFactory.java:221)
	uk.gov.gchq.gaffer.rest.factory.AbstractExamplesFactory.getElements(AbstractExamplesFactory.java:344)
	uk.gov.gchq.gaffer.rest.factory.AbstractExamplesFactory.generateExamples(AbstractExamplesFactory.java:90)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base&#47;jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base&#47;java.lang.reflect.Method.invoke(Method.java:566)
	org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
	org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
	org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	java.base&#47;java.util.concurrent.FutureTask.run(FutureTask.java:264)
	org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:666)
	org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
	org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
	org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
	org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:59)
	org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:758)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:721)
	org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:691)
	org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:160)
	org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:30)
	org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:105)
	org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:260)
	org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:51)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:86)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:69)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:38)
	org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:247)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	uk.gov.gchq.gaffer.rest.filter.OriginFilter.doFilter(OriginFilter.java:42)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.58</h3></body></html>
```

### PR DESCRIPTION
**Pull request by tb06904**
This fixes the main issue described in the issue where a potential null pointer is thrown if 'directed' field is missing from a schema, the bug comes from the `AbstractExamplesFactory` not accounting for a potential null pointer.

The original issue does mention other config errors are ignored but it does seem like the errors are throw correctly at start up if the config is incorrect as the schema is validated and will fail there, failures will be slightly buried in the REST API start up logs but not too sure much can done about that as spring boot is wrapping the whole start up process anyways. 

Tidied few bits too.

# Related issue

- Resolve #3139

### CODE REVIEW

**Review by GCHQDeveloper314 — COMMENTED** [review]
Although not part of the issue itself, some of the existing code changed in this PR never had tests. Given recent issues with this class, higher test coverage would be good to have.

For the original issue's wording, this is a bit confusing as there's nothing much that can be done about how exceptions are thrown.

**Comment by tb06904** [comment]
> Although not part of the issue itself, some of the existing code changed in this PR never had tests. Given recent issues with this class, higher test coverage would be good to have.
> 
> For the original issue's wording, this is a bit confusing as there's nothing much that can be done about how exceptions are thrown.

True its probably worth adding a few tests around this class anyways, I'll add some in.

File: rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java [hunk 1]
```diff
@@ -135,43 +135,43 @@ public Operation generateExample(final Class<? extends Operation> opClass) throw
...
+                final List l = Arrays.asList(clazz.getEnumConstants());
+                if (!l.isEmpty()) {
+                    value = Enum.valueOf(clazz, l.get(0).toString());
                 } else {
                     value = clazz.newInstance();
                 }
-            } catch (final InstantiationException | IllegalAccessException e) {
-                value = null;
+            } else {
+                value = clazz.newInstance();
```
Comment (GCHQDeveloper314) [inline rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java:167]: This is ok for Java 8, but [for Java 9+ it is deprecated](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#newInstance()). The recomended solution is compatible with Java 8 so I'd suggest using it in these changes.

File: rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java [hunk 2]
```diff
@@ -135,43 +135,43 @@ public Operation generateExample(final Class<? extends Operation> opClass) throw
...
+            } else if (Date.class.equals(clazz)) {
+                value = new Date(System.currentTimeMillis() - 10000 + uniqueId);
+            } else if (boolean.class.equals(clazz)) {
+                value = uniqueId % 2 == 0;
+            } else if (BinaryOperator.class.equals(clazz)) {
+                value = new First();
+            } else if (clazz.isEnum()) {
+                final List l = Arrays.asList(clazz.getEnumConstants());
+                if (!l.isEmpty()) {
+                    value = Enum.valueOf(clazz, l.get(0).toString());
```
Comment (GCHQDeveloper314) [inline rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java:162]: While not really part of the changes in this PR, this stuff wasn't covered before and I'm unsure of what it's doing and if it will work properly.

**Review by GCHQDeveloper314 — COMMENTED** [review]
Coverage is better now, just a couple of minor comments on the existing code.

File: rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java (hunk 2 above)
Comment (tb06904) [reply rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java:162]: True this section from what I can tell is mostly to do with creating an Entity with the `vertex` type defined in the schema e.g. if it was meant to be an `Integer` this generates an Entity with that value for its `vertex` field. With that I can only assume this bit is for if the schema has defined an `Enum` as the type for `vertex` it creates one with the first value in the `Enum`.

Comment (GCHQDeveloper314) [reply rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java:162]: That makes sense. I don't much like this code as it also uses rawtypes when `Class<?>` should be used. I think I might raise a new issue to look at those aspects of this class. Not something which needs to be done in this PR.

**Review by GCHQDeveloper314 — APPROVED** [review]

**Review by t92549 — APPROVED** [review]
