### PR TITLE
PR requests with issues

### LINKED ISSUE #3045: MergeSchema is ignoring SchemaExceptions
**Describe the bug**
When the `MergeSchema` class applies the `Schema.BaseBuilder.merge` function, it catches `SchemaException`s. This is because it will retry while ignoring vertex serialisers if the error is to do with vertex serialisers:
https://github.com/gchq/Gaffer/blob/e90fba0cb33ca23ab60cd1e2c175dfd29801fde1/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/MergeSchema.java#L56-L65
However, if the `SchemaException` is unrelated to vertex serialisers, I would expect the exception to still be thrown:
```java
if (e.getMessage().contains(Schema.UNABLE_TO_MERGE_SCHEMAS_CONFLICT_WITH_VERTEX_SERIALISER_OPTIONS_ARE)) {
    // handle the vertex serialiser issue...
} else {
    // throw other types of SchemaException
    throw e
}
```
This is not the case.

**Additional context**
If you simply add this else block in, tests will start to fail. These tests are [FederatedStoreVisibilityTest](https://github.com/gchq/Gaffer/blob/e90fba0cb33ca23ab60cd1e2c175dfd29801fde1/store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreVisibilityTest.java) (issue: https://github.com/gchq/Gaffer/issues/1834) and [FederatedStoreSchemaOverlapTest](https://github.com/gchq/Gaffer/blob/e90fba0cb33ca23ab60cd1e2c175dfd29801fde1/store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaOverlapTest.java) (issue: https://github.com/gchq/Gaffer/issues/2767). These tests were added as part of Gaffer 2 development to codify the new FederatedStore behaviour, however, we did not realise this behaviour was happening as a result of a bug.

**Suggested fix**
`MergeSchema` should be fixed and extended to manage all types of SchemaException.
When a SchemaException happens due to conflicting visibility property names, this can probably be intentionally ignored with a warning message.
When a SchemaException happens due to conflicting types for the same property in the same group across two subgraphs, things are more complicated. Perhaps, if the type definitions are the same the error can be ignored, and if not they can be de-duplicated. 
This will likely need work on `Schema.BaseBuilder.validateSharedGroupsAreCompatible`

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related issue

- Resolve #3045

### CODE REVIEW

File: core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/exception/SchemaException.java [hunk 1]
```diff
@@ -35,4 +36,19 @@ public SchemaException(final String message) {
     public SchemaException(final String message, final Throwable e) {
         super(message, e, BAD_REQUEST);
     }
+
+    public SchemaException preAppendToMessage(final String appendToMessage) {
+        if (null == this.appendToMessage) {
+            this.appendToMessage = new StringBuilder();
+        }
+        //preAppend
```
Comment (t92549) [inline core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/exception/SchemaException.java:44]: This is called prepend

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java [hunk 2]
```diff
@@ -350,8 +348,10 @@ public CHILD_CLASS merge(final Schema schema) {
 
                     mergeConfig(thatSchema);
 
+                } catch (final SchemaException e) {
+                    throw e.preAppendToMessage(ERROR_MERGING_SCHEMA_DUE_TO);
```
Comment (t92549) [inline core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java:352]: A little confused by this method when straight afterwards `throw new SchemaException(ERROR_MERGING_SCHEMA_DUE_TO + e.getMessage(), e);` is used

Comment (tb06904) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java:352]: This is used to add some additional information to any exceptions thrown that extend the `SchemaException` type without loosing the sub exception type which is caught and handled in the `MergeSchema` class.

Technically this is kind of the same as doing:

```java
throw e.getCause().getClass().getDeclaredConstructor().newInstance("something" + e.getMessage());`
```

Comment (t92549) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java:352]: Okay, this does look less verbose than what you showed, so makes sense. Maybe naming could be better though

Comment (tb06904) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java:352]: I agree, to be honest it might be simpler now to just catch the exact exceptions now there is only three to eliminate the need for custom internal prepend method e.g.
```java
catch (SplitElementGroupDefException e) {
    throw new SplitElementGroupDefException("extra info" + e.getMessage(), e);
} catch (VertexSerialiserSchemaException e) {
    throw new VertexSerialiserSchemaException("extra info" + e.getMessage(), e);
} catch (VisibilityPropertySchemaException e) {
    throw new VisibilityPropertySchemaException("extra info" + e.getMessage(), e);
}
```

File: core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/exception/SchemaException.java (hunk 1 above)
Comment (GCHQDev404) [reply core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/exception/SchemaException.java:44]: lol

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java (hunk 2 above)
Comment (t92549) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java]: But they add different information depending on the type

Comment (GCHQDev404) [reply core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java]: This line is adding the same information.
