### PR TITLE
Gh-3353: Ensure user info passed in GafferPop

### LINKED ISSUE #3353: Make sure user and info is passed in GafferPop
**Describe the bug**
The user is not properly propagated when running Gremlin queries it always uses the default user.

### PR DESCRIPTION
**Pull request by tb06904**
Addresses some of the issues with passing information from the REST API to gafferpop by ensuring each request now has its own instance of the tinkerpop graph layer so the variables are unique per request. Also stops the user from being reset immediately by the custom GraphStep.

Few other minor bits of tidying and improvements to otel logging.

# Related issue

- Resolve #3353

### CODE REVIEW

File: core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java [hunk 1]
```diff
@@ -320,10 +320,11 @@ private <O> GraphResult<O> _execute(final StoreExecuter<O> storeExecuter, final
         // OpenTelemetry hooks
         Span span = OtelUtil.startSpan(
             this.getClass().getName(),
-            "Graph Request: " + clonedOpChain.toOverviewString());
+            "Graph Request: " + clonedContext.getJobId());
```
Comment (p29876) [inline core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java:323]: Will this this still work as expected now that synchronous queries don't get a job id?

File: rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/handler/GremlinWebSocketHandler.java [hunk 2]
```diff
@@ -86,24 +84,23 @@ public class GremlinWebSocketHandler extends BinaryWebSocketHandler {
             new SimpleEntry<>(SerTokens.MIME_GRAPHSON_V3, new GraphSONMessageSerializerV3()),
             new SimpleEntry<>(SerTokens.MIME_JSON, new GraphSONMessageSerializerV3()))
         .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
-
-    private final ExecutorService executorService = Context.taskWrapping(Executors.newFixedThreadPool(4));
-    private final ConcurrentBindings bindings = new ConcurrentBindings();
-    private final Long requestTimeout;
+    // Shared thread pool for executing gremlin queries in
+    private final ExecutorService executorService = Context.taskWrapping(Executors.newFixedThreadPool(8));
```
Comment (p29876) [inline rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/handler/GremlinWebSocketHandler.java:88]: and again

File: core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java (hunk 1 above)
Comment (tb06904) [reply core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java:323]: It seems even if not given one a context will always have a `JobId` its part of the constructor.

File: rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GremlinController.java [hunk 3]
```diff
@@ -98,19 +97,17 @@ public class GremlinController {
...
 
     private static final Logger LOGGER = LoggerFactory.getLogger(GremlinController.class);
-    private static final String GENERAL_ERROR_MSG = "Failed to evaluate Gremlin query: ";
-
-    private final ConcurrentBindings bindings = new ConcurrentBindings();
-    private final ExecutorService executorService = Context.taskWrapping(Executors.newFixedThreadPool(4));
-    private final Long requestTimeout;
+    private static final String GENERAL_ERROR_MSG = "Gremlin query failed: ";
+    // Shared thread pool for executing gremlin queries in
+    private final ExecutorService executorService = Context.taskWrapping(Executors.newFixedThreadPool(8));
```
[the remark this answers is not in the document]
Comment (tb06904) [reply rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GremlinController.java:102]: Did think that but I think as we are doing synchronous calls to the executor (always calling `.get()` immediately) the amount of threads stays consistent. Making the pool here is mostly to save on initialisation time of the `GremlinExecutor` as if not supplied a thread pool it creates its own.

**Review by p29876 — APPROVED** [review]

**Review by cn337131 — DISMISSED** [review]

**Review by cn337131 — APPROVED** [review]
