### PR TITLE
Gh 2890 cache service static instance bug

### LINKED ISSUE #2890: Cache Service Static Instance Bug
**Describe the bug**
Cache service is Static, which means that any attempt to use a new cache can wipe/swap the cache.
This is horrendous for FederatedStore which uses the cache to store graphs. This is an Ancient bug but since the internal GraphStorage java object has been removed since #2595 this bug has appeared during docker containers testing.

Truth Table of error and behaviour below.

**To Reproduce**
  | AddGraph with no Cache | AddGraph with HashMap Cache | AddGraph with JCS Cache
-- | -- | -- | --
FederatedStore is currently using HashMap Cache | Graph is added to HashMap Cache | The Cache service continues to be HashMap Cache, the cache is initialised, FederatredStore only contains this new graph. | The Cache service is switched to JCS Cache, the cache is initialised, JCS cache is loaded from disc, FederatredStore contains this new graph and anything pre-existing in the cache.
FederatedStore is currently using JCS Cache | Graph is added to JCS Cache | The Cache service is switched to HashMap Cache, the cache is initialised, FederatredStore only contains this new graph. | The Cache service continues to be JCS Cache, the cache is initialised, JCS cache is loaded from disc, FederatredStore contains this new graph and anything pre-existing in the cache.

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related Issue

- Resolve #2890

### CODE REVIEW

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java [hunk 1]
```diff
@@ -98,10 +100,11 @@ private void overwriteCacheProperty(final OP operation, final Store store) {
          * FederatedStore can't survive if a subgraph changes the static
          * cache to another cache, or re-initialises the cache.
          */
+        final String cacheServiceClass = isNull(store.getProperties()) ? null : store.getProperties().getCacheServiceClass(CACHE_SERVICE_CLASS_DEFAULT);
         final StoreProperties storeProperties = operation.getStoreProperties();
```
Comment (GCHQDeveloper314) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java:104]: One line uses `store.getProperties()`, the other `operation.getStoreProperties()`. Isn't this the same thing? Better to be consistent.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java [hunk 2]
```diff
@@ -98,10 +100,11 @@ private void overwriteCacheProperty(final OP operation, final Store store) {
...
-        if (nonNull(storeProperties) && storeProperties.containsKey(CACHE_SERVICE_CLASS)) {
-            LOGGER.info(String.format("%s is removing %s from properties of the operation and substituting the FederatedStore's cache", this.getClass().getSimpleName(), CACHE_SERVICE_CLASS));
-            storeProperties.setCacheServiceClass(store.getProperties().getCacheServiceClass());
+        if (nonNull(storeProperties) && !storeProperties.getCacheServiceClass(cacheServiceClass).equals(cacheServiceClass)) {
+            LOGGER.info(String.format("Removing %s from properties of the operation and substituting the FederatedStore's cache", CACHE_SERVICE_CLASS));
+            storeProperties.setCacheServiceClass(cacheServiceClass);
             operation.setStoreProperties(storeProperties);
```
Comment (GCHQDeveloper314) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java:108]: I would have thought these were the same too, or pointing to the same object?

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java (hunk 1 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java:104]: no one is FederatedStores Property the other is the Property of the store being added.

I want overwrite with one.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java [hunk 3]
```diff
@@ -98,10 +100,11 @@ private void overwriteCacheProperty(final OP operation, final Store store) {
          * FederatedStore can't survive if a subgraph changes the static
          * cache to another cache, or re-initialises the cache.
          */
+        final String cacheServiceClass = isNull(store.getProperties()) ? null : store.getProperties().getCacheServiceClass(CACHE_SERVICE_CLASS_DEFAULT);
         final StoreProperties storeProperties = operation.getStoreProperties();
-        if (nonNull(storeProperties) && storeProperties.containsKey(CACHE_SERVICE_CLASS)) {
-            LOGGER.info(String.format("%s is removing %s from properties of the operation and substituting the FederatedStore's cache", this.getClass().getSimpleName(), CACHE_SERVICE_CLASS));
-            storeProperties.setCacheServiceClass(store.getProperties().getCacheServiceClass());
+        if (nonNull(storeProperties) && !storeProperties.getCacheServiceClass(cacheServiceClass).equals(cacheServiceClass)) {
+            LOGGER.info(String.format("Removing %s from properties of the operation and substituting the FederatedStore's cache", CACHE_SERVICE_CLASS));
```
Comment (t92549) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java:106]: So this makes the subgraph use the same cache as the federated store? I thought this is what we were trying to avoid?

Comment (t92549) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java:106]: Because it is still static all subgraphs must use the same static instance as the federated store. They now will use a suffix though to avoid collision

**Review by t92549 — APPROVED** [review]
