### PR TITLE
gh-2809 federatedstore fix incorrect test refracting

### LINKED ISSUE #2809: FederatedStore fix incorrect test refracting
FederatedStoreGraphVisibilityTest was incorrectly refactored in previous alpha4 test.

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related Issue

- Resolve #2809

### CODE REVIEW

**Review by t92549 — DISMISSED** [review]
Nice refactor of `GraphLibrary` and tests make a lot more sense now

File: core/store/src/main/java/uk/gov/gchq/gaffer/store/library/GraphLibrary.java [hunk 1]
```diff
@@ -327,44 +327,47 @@ private void nullCheck(final String graphId, final Schema schema, final StorePro
 
 
     public Schema resolveSchema(final Schema schema, final List<String> parentSchemaIds) {
-        Schema resultSchema = null;
+        Schema.Builder rtn = new Schema.Builder();
```
Comment (GCHQDeveloper314) [inline core/store/src/main/java/uk/gov/gchq/gaffer/store/library/GraphLibrary.java:330]: Why is this `rtn`. It's not being returned, one of it's methods run and the result of that is returned. Even if it was being returned, `rtn` is not a good name.
