### PR TITLE
Gh-3061: Ensure ToHllSketch functions copy

### LINKED ISSUE #3061: ToHllSketch functions do not copy from other HllSketch
**Describe the bug**
`ToHllSketch` and `IterableToHllSketch` can both be intitialised with another HllSketch. It should be copied but is not.
Additionally, these fields should be JsonIgnored as they won't be used over the rest api and wouldn't work anyway.

### PR DESCRIPTION
**Pull request by t92549**
# Related issue

- Resolve #3061

### CODE REVIEW

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java [hunk 1]
```diff
@@ -44,14 +46,17 @@ public ToHllSketch(final int logK) {
         this.logK = logK;
     }
 
-    public ToHllSketch(final HllSketch hllSketch) {
-        this.hllSketch = hllSketch;
+    public ToHllSketch(final HllSketch initHllSketch) {
+        this.initHllSketch = initHllSketch;
```
Comment (tb06904) [inline library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java:50]: Out of curiosity could the copy be taken here instead if not null? e.g.
```java
if (initHllSketch != null) {
    this.hllSketch = initHllSketch.copy();
}
```

File: library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketchTest.java [hunk 2]
```diff
@@ -112,6 +112,24 @@ public void shouldCorrectlyCreateFromAnotherHllSketch() {
...
 
+    @Test
+    public void shouldCorrectlyCopyAnotherHllSketch() {
+        // Given
+        final HllSketch anotherSketch = new HllSketch();
+        anotherSketch.update("second");
+        anotherSketch.update("third");
+
+        IterableToHllSketch iterableToHllSketch = new IterableToHllSketch(anotherSketch);
+        final List<Object> input = Arrays.asList("one", "one", "two", "two", "three");
```
Comment (tb06904) [inline library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketchTest.java:123]: Pretty minor but could be `List<String>` instead?

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java (hunk 1 above)
Comment (t92549) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java:50]: I guess my thinking was someone could use the setter to overwrite it as null but that seems very unlikely. What do you think?

File: library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketchTest.java (hunk 2 above)
Comment (t92549) [reply library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketchTest.java:123]: When I do that `iterableToHllSketch.apply` is unhappy as it specifies `Iterable<Object>`.

Comment (tb06904) [reply library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketchTest.java:123]: Fair makes sense

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java (hunk 1 above)
Comment (t92549) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java:50]: I think it gets messy if another constructor is used

Comment (tb06904) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java:50]: Not quite sure I follow, do you mean by subclasses of this class? All I was thinking is it sounds like you want to allow an existing HllSketch to be used to init the one associated with this class but then just make sure not modify that original object so make a copy of it before using? This could be done in the constructor then the set method just does the same.

Comment (t92549) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java:50]: It could be done there, but you would still need this null check in the apply in case someone uses one of the other constructors.

Comment (tb06904) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java:50]: You can call the other constructors from one of the overloaded ones with `this()` (I edited my comment to add an example)

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java [hunk 3]
```diff
@@ -94,6 +99,8 @@ public HllSketch getHllSketch() {
     }
 
     public void setHllSketch(final HllSketch hllSketch) {
-        this.hllSketch = hllSketch;
+        if (hllSketch != null) {
+            this.hllSketch = hllSketch.copy();
+        }
```
Comment (GCHQDeveloper314) [inline library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java:104]: Previously this had no usages. I'm not sure that changing it to ignore if the sketch is already set is the best approach.

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java [hunk 4]
```diff
@@ -35,24 +36,28 @@
...
     public IterableToHllSketch() {
+        if (hllSketch == null) {
+            hllSketch = new HllSketch(logK);
+        }
     }
 
     public IterableToHllSketch(final int logK) {
-        this.logK = logK;
+        setLogK(logK);
+        if (hllSketch == null) {
```
Comment (GCHQDeveloper314) [inline library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java:50]: As this is the constructor, won't `hllSketch` always be null?

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java [hunk 5]
```diff
@@ -35,24 +36,28 @@
 @Summary("Creates a new HllSketch instance and initialises it from the given iterable")
 public class IterableToHllSketch extends KorypheFunction<Iterable<Object>, HllSketch> {
     private int logK = DEFAULT_LOG_K;
+    @JsonIgnore
     private HllSketch hllSketch;
 
     public IterableToHllSketch() {
+        if (hllSketch == null) {
```
Comment (GCHQDeveloper314) [inline library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java:43]: As this is the constructor, won't `hllSketch` always be null?

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java
Comment (GCHQDeveloper314) [inline library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java:1]: See comment in other file relating to constructors.

File: library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java (hunk 3 above)
Comment (tb06904) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java:104]: I don't think that is what this change is doing, its checking if the newly supplied sketch is not null.

Comment (GCHQDeveloper314) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java:104]: You're right. This makes more sense, but I still question doing it. There's not much reason you'd want to set to `null`, but now if someone does want to do that it won't work and they will not know why unless they look at the code.

Comment (tb06904) [reply library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java:104]: I'm guessing its to avoid the null pointer exception as you can't call `copy()` on null as, a thought there could be an else statement for setting to null?

**Review by tb06904 — DISMISSED** [review]

**Review by GCHQDeveloper314 — DISMISSED** [review]

**Review by tb06904 — APPROVED** [review]
