### PR TITLE
Gh-3209: GetAll Limit fails on Proxy Store

### LINKED ISSUE #3209: Issues with GafferPop's GetAllElements limitting on proxy stores
**Describe the bug**
This was found testing some of the standard gremlin queries but via the proxy store, there is essentially three smaller but related issues.

- Proxy store can't accept operation chains that have unmodifiable options or null options this needs making more robust.
- The  `GafferPopGraphStep` doesnt actually run the right `vertex()` method on the graph class due to it wrapping the array in a list which pushes it to an override method.
The apache utils method for checking the size of the returned iterator seems to have casting issues from LinkedList to Element when using proxy store this could be some deserialisation issue

### PR DESCRIPTION
**Pull request by tb06904**
Fixes most of the issues in the original issue, two minor fixes:
1. ensures the correct method is called in the `GafferPopGraphStep` 
2. Prevents `null` operation chain options.

Added work around to main serialisation error in the proxy store so that it attempts to deserialise element iterators. This will be fixed in a larger rework of the proxy store so that it does not need to double deserialise.

# Related issue

- Resolve #3209

### CODE REVIEW

File: core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java [hunk 1]
```diff
@@ -184,7 +184,11 @@ public Map<String, String> getOptions() {
 
     @Override
     public void setOptions(final Map<String, String> options) {
-        this.options = options;
+        if (options == null) {
+            this.options = new HashMap<>();
```
Comment (GCHQDeveloper314) [inline core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java:188]: Why do this if it is now set to a `HashMap` by default; is this in case it's set to something else already?

I'm guessing the new default `HashMap` is because of interaction with another class?

File: library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java [hunk 2]
```diff
@@ -540,8 +540,9 @@ public Iterator<Vertex> adjVerticesWithView(final Iterable<Object> vertexIds, fi
     public Iterator<Edge> edges(final Object... elementIds) {
         final boolean getAll = null == elementIds || 0 == elementIds.length;
 
-        final Output<Iterable<? extends Element>> getOperation;
+        final OperationChain<Iterable<? extends Element>> getOperation;
         if (getAll) {
+            LOGGER.warn("Requested a GetAllElements results will be truncated to: {}.", getAllElementsLimit);
```
Comment (GCHQDeveloper314) [inline library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java:545]:
```suggestion
            LOGGER.warn("Requested a GetAllElements, results will be truncated to: {}.", getAllElementsLimit);
```

File: store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java [hunk 3]
```diff
@@ -36,8 +42,21 @@ public O deserialise(final String jsonString) throws SerialisationException {
...
-            return JSONSerialiser.deserialise(encodeString(jsonString), typeReference);
+            // For some operations like 'Limit' we may not know the output type up front so it
+            // will be left as a generic '?', this means some objects will not be deserialised correctly.
+            try {
+                // Check if we can deserialise to common outputs like list of elements.
+                // This is a workaround until proxy store has been refactored
+                if (typeReference.getType().getTypeName().equals(Iterable.class.getName() + "<?>")) {
+                    return (O) JSONSerialiser.deserialise(encodeString(jsonString), new TypeReferenceImpl.IterableElement());
+                } else {
+                    return JSONSerialiser.deserialise(encodeString(jsonString), typeReference);
```
Comment (GCHQDeveloper314) [inline store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java:53]: This line is duplicated in the catch, I'm wondering if it could be used in a `finally` instead?

File: library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java [hunk 4]
```diff
@@ -411,12 +412,11 @@ public Iterator<Vertex> vertices(final Object... vertexIds) {
                 .map(e -> (Vertex) e)
                 .iterator();
 
-        final int resultSize = IterableUtils.size(translatedResults);
-        if (getAll && resultSize >= getAllElementsLimit) {
-            LOGGER.warn("Result size is equal to configured limit ({}). Results may have been truncated", getAllElementsLimit);
+        if (getAll && IterableUtils.size(translatedResults) > getAllElementsLimit) {
+            LOGGER.warn(
```
Comment (p29876) [inline library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java:416]: Should this ever happen? Is the size > limit the results haven't been truncated

File: core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java (hunk 1 above)
Comment (tb06904) [reply core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java:188]: Its mostly due to the proxy store as it was asking for the current options (which were null) then attempting to add to them which hit a null pointer. It's really its more a bug here as shouldn't be able to set the options to null they should just be blank/empty.

File: library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java (hunk 4 above)
Comment (tb06904) [reply library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java:416]: Good spot, I removed this section when debugging so just been added back slightly wrong

File: store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java (hunk 3 above)
Comment (tb06904) [reply store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java:53]: Think that would be incorrect use of a finally block as you are saying you always want to run whatever is in the finally block whereas, in this case we only want to run it conditionally as a fallback.

Comment (GCHQDeveloper314) [reply store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java:53]: I was thinking of something like this:
```
O rtn = null;
try {
    if (case) {
        rtn = ...
    }
} catch (e) {
    LOGGER.error(...)
} finally {
    if (rtn == null) {
        rtn == fallback
    }
    return rtn;
}
```
Though this might not be a great idea just to save some duplication.

Comment (tb06904) [reply store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java:53]: Fair I see what you mean, though I'm not sure if its really worth changing especially as this will all be made obsolete under proposed redesign of proxy store

**Review by GCHQDeveloper314 — APPROVED** [review]

**Review by p29876 — APPROVED** [review]

File: store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java [hunk 5]
```diff
@@ -36,8 +42,21 @@ public O deserialise(final String jsonString) throws SerialisationException {
...
+                }
+            } catch (final SerialisationException e) {
+                // The input is likely a valid JSON value type, so process using the deserialiser
+                LOGGER.error("Unable to deserialse Iterable<?> as Iterable<Elements> using default deserialisation", e);
+                return JSONSerialiser.deserialise(encodeString(jsonString), typeReference);
```
Comment (GCHQDev404) [inline store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java:58]: "try" at line 53 "return JSONSerialiser.deserialise(encodeString(jsonString), typeReference);"
"catch" line 58 "return JSONSerialiser.deserialise(encodeString(jsonString), typeReference);"

the scoping of this try catch does not seem correct.

**Review by GCHQDev404 — CHANGES_REQUESTED** [review]

File: core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java [hunk 6]
```diff
@@ -66,7 +66,7 @@
 public class OperationChain<OUT> implements Output<OUT>,
         Operations<Operation> {
     private List<Operation> operations;
-    private Map<String, String> options;
+    private Map<String, String> options = new HashMap<>();
```
Comment (GCHQDev404) [inline core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java:69]: This might change the string representation of JSON of operation chains. It might always display 
`"options":{}` which is verbose.

File: store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java (hunk 5 above)
Comment (GCHQDeveloper314) [reply store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java:58]: Was discussed in [a previous comment here](https://github.com/gchq/Gaffer/pull/3214#discussion_r1603322513). Ideally could be better but is only temporary until a better proxystore is done.

File: core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java (hunk 6 above)
Comment (GCHQDeveloper314) [reply core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java:69]: See the discussion [in this comment](https://github.com/gchq/Gaffer/pull/3214#discussion_r1603314029), this is a good point though. It would likely be better to make further changes in the Proxy Store instead.

Comment (tb06904) [reply core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java:69]: Surely that would be better to have the options field displayed as you would hit the same issue where the key would be missing if trying to parse the JSON. It is arguably safer to prevent the null pointer from ever occurring than to expect every thing else to handle it.
