### PR TITLE
gh-2435 federated store change graph id table name fix

### LINKED ISSUE #2435: FederatedStore ChangedGraphId with updated Cache will result in an orphaned table of data.
The issue gh-2422 to make the changes persist in Cache will cause the FederatedStore to restart with new graphId pointing to NEW TABLES in Accumulo. Causing orphaned tables with old graphId names and data.

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related Issue

- Resolve #2435

### CODE REVIEW

**Review by p3430233 — APPROVED** [review]

**Comment by n3101** [comment]
@GCHQDev404 said: "this fails on github but passes locally."

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java [hunk 1]
```diff
@@ -598,23 +609,68 @@ private boolean changeGraphId(final String graphId, final String newGraphId, fin
...
-                    .build(), key);
+                    .build();
+            this.put(newGraphSerialisable, key);
+
+            //Update cache
+            if (isCacheEnabled()) {
+                try {
+                    federatedStoreCache.addGraphToCache(newGraphSerialisable, key, true/*true because graphLibrary should have throw error*/);
+                } catch (final CacheOperationException e) {
+                    //TODO FS recovery
```
Comment (t92549) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:652]: Is this still TODO?

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java [hunk 2]
```diff
@@ -598,23 +609,68 @@ private boolean changeGraphId(final String graphId, final String newGraphId, fin
...
                     .graph(graphToMove)
                     .config(configWithNewGraphId)
-                    .build(), key);
+                    .build();
+            this.put(newGraphSerialisable, key);
+
+            //Update cache
+            if (isCacheEnabled()) {
+                try {
+                    federatedStoreCache.addGraphToCache(newGraphSerialisable, key, true/*true because graphLibrary should have throw error*/);
```
Comment (t92549) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:650]: Comment on new line

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java [hunk 3]
```diff
@@ -598,23 +609,68 @@ private boolean changeGraphId(final String graphId, final String newGraphId, fin
                 }
             }
 
-            final GraphConfig configWithNewGraphId = new GraphConfig.Builder()
-                    .json(new GraphSerialisable.Builder().graph(graphToMove).build().getConfig())
-                    .graphId(newGraphId)
-                    .build();
+            //Update Tables
+            String storeClass = graphToMove.getStoreProperties().getStoreClass();
+            if (nonNull(storeClass) && storeClass.startsWith(AccumuloStore.class.getPackage().getName())) {
```
Comment (t92549) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:614]: This approach isn't super portable, will it work for all other stores? e.g. HBase

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java [hunk 4]
```diff
@@ -598,23 +609,68 @@ private boolean changeGraphId(final String graphId, final String newGraphId, fin
...
+                try {
+                    AccumuloProperties tmpAccumuloProps = (AccumuloProperties) graphToMove.getStoreProperties();
+                    Connector connection = TableUtils.getConnector(tmpAccumuloProps.getInstance(),
+                            tmpAccumuloProps.getZookeepers(),
+                            tmpAccumuloProps.getUser(),
+                            tmpAccumuloProps.getPassword());
+
+                    if (connection.tableOperations().exists(graphId)) {
+                        connection.tableOperations().offline(graphId);
+                        connection.tableOperations().clone(graphId, newGraphId, true, null, null);
```
Comment (t92549) [inline store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:628]: Rather than cloning and deleting the table which is costly for large amounts of data, can't you do something like `connection.tableOperations().rename(graphId, newGraphId);`?

Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:628]: Accumulo is smarter that that, the data doesn't copy.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 3 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:614]: No it won't, this is a code block is for Accumulo with Accumulo specific commands.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 4 above)
Comment (t92549) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:628]: Fair enough, but since this is a rename operation, would it not just make sense to rename it instead of cloning and deleting?

Comment (t92549) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:628]: https://accumulo.apache.org/1.5/apidocs/org/apache/accumulo/core/client/admin/TableOperations.html
I was able to swap it with rename and it worked just fine

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 2 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:650]: Any objections to inline comments?
I inlined next to variable so that comment doesn't get lost with any refactoring or moving,

Comment (t92549) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:650]: I think it just looks strange and makes the line really long but if there is a precedent than that's okay

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 1 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:652]: Kinda.
I think due to exceptions that is kinda hard logic to recover the graphs and trust that it was successfully recovered. Due to recovery could also throw exceptions.
I think meaningful Logging and get Admin to jump in and fix things is the best solution for recovery.

thoughts?

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 3 above)
Comment (t92549) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:614]: Maybe there should be a smarter solution then? Otherwise this will just be a big if statement within the FederatedStore to make sure it works for all other store types

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java [hunk 5]
```diff
@@ -48,7 +58,8 @@
     public static final User ADMIN_USER = new User("admin", Collections.EMPTY_SET, Sets.newHashSet("AdminAuth"));
     public static final User NOT_ADMIN_USER = new User("admin", Collections.EMPTY_SET, Sets.newHashSet("NotAdminAuth"));
 
-    private static Class currentClass = new Object() { }.getClass().getEnclosingClass();
+    private static Class currentClass = new Object() {
+    }.getClass().getEnclosingClass();
```
[the remark this answers is not in the document]
Comment (GCHQDev404) [reply store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java:62]: YES!

[the remark this answers is not in the document]
Comment (GCHQDev404) [reply store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java:62]: should be `FederatedAdminIT.class.getEnclosingClass();`

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 1 above)
Comment (t92549) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:652]: Yeah I think throwing an exception explaining the cache broke is okay. I just think committing `//TODO FS recovery` to master isn't too descriptive

File: store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedStoreRecursionIT.java [hunk 6]
```diff
@@ -64,7 +64,7 @@
     private User user = new User();
 
     @Test
-    @Timeout(value = 60)
+    @Timeout(value = 20000)
```
[the remark this answers is not in the document]
Comment (GCHQDev404) [reply store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedStoreRecursionIT.java:67]: should be milliseconds = 20 seconds

[the remark this answers is not in the document]
Comment (t92549) [reply store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedStoreRecursionIT.java:67]: https://junit.org/junit5/docs/5.5.0-RC2/api/org/junit/jupiter/api/Timeout.html
Default is indeed seconds in JUnit 5

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 4 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:628]: what is this witchcraft. I was unable to find a rename.
or am I thinking of the command line Accumulo api.
maddening.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 3 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:614]: Agreed. But I don't know if this problem exist with other stores. (probably does)
In the interim I wanted to get a 95% solution in.
I'm happy to add a comment/new ticket

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 2 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:650]: I'm on the fence. It has happened before. I can change it since I'm changing other things.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 1 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:652]: The TODO wasn't for keeps. It was to prompt an examination.

File: store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java (hunk 2 above)
Comment (GCHQDev404) [reply store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java:650]: I was on the fence. Its easy to skip with the eye if skimming code but available if you read the details of the method arguments. There is precedent in code.
